# https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options

call_parentheses = "None"
collapse_simple_statement = "Never"
column_width = 120
indent_type = "Spaces"
indent_width = 4
line_endings = "Unix"
quote_style = "ForceDouble"

[sort_requires]
enabled = true
